const {
	ALPHA_VANTAGE_API_KEY,
	ALPHA_VANTAGE_BASE_URL,
	FINANCIAL_MODELING_GREP_API_KEY,
	FMPCLOUD_API_KEY,
	FMPCLOUD_BASE_URL,
	PORT 
} = require('./config');
const { getCompanyTickerFromURL } = require('./getCompanyTicker');

module.exports = {
	ALPHA_VANTAGE_API_KEY,
	ALPHA_VANTAGE_BASE_URL,
	FINANCIAL_MODELING_GREP_API_KEY,
	FMPCLOUD_API_KEY,
	FMPCLOUD_BASE_URL,
	PORT,
	getCompanyTickerFromURL,
};
